name: 24-hour-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --header "Content-Type: application/json" \
          --url 'https://grimm-feeder.vercel.app/api/feed' \
          --data '{"status":"false","time":"morning"}'
